apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-container
          image: tamal008/express_app:1.0.1
          ports:
            - containerPort: 3000
