apiVersion: v1
kind: Pod
metadata:
  name: traffic-pod
  labels:
    name: trafic-app
spec:
  containers:
    - name: trafic-container
      image: tamal008/traffic_gen:1.0.2
      args:
        - "google.com"
        - "1"
