apiVersion: v1
kind: Pod
metadata:
  name: traffic-pod
  labels:
    name: trafic-app
spec:
  containers:
    - name: trafic-container
      image: tamal008/traffic_gen:1.0.4
      args:
        - "express-svc:3000"
        - "1"
